name = "CNNSeq2exp"
uuid = "ca0eaa81-961d-4b24-843c-8575ada746de"
authors = ["anon"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
